src/SysMatriculas.Web/Controllers/CursoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SysMatriculas.Dominio;
using SysMatriculas.Dominio.Requests;
using SysMatriculas.Dominio.Responses;
using SysMatriculas.Negocio.Services.Interfaces;
using SysMatriculas.Persistencia.DTOs.DataTables;
using SysMatriculas.Web.Extensions;
using SysMatriculas.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SysMatriculas.Web.Controllers
{
    [Authorize(Roles = "Coordenador")]
    public class CursoController : Controller
    {
        private ICursoService _cursoService;
        private ICurriculoService _curriculoService;

        public CursoController(
            ICursoService cursoService,
            ICurriculoService curriculoService)
        {
            _cursoService = cursoService;
            _curriculoService = curriculoService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Listar(DataTableRequest request)
        {
            try
            {
                var cursosPaginados = await _cursoService.ObterListaPaginada(request);
                return Json(new
                {
                    request.draw,
                    recordsTotal = cursosPaginados.RecordsTotal,
                    recordsFiltered = cursosPaginados.RecordsFiltered,
                    data = cursosPaginados.Itens
                });
            }
            catch (Exception ex)
            {
                return Json(new ErroResponse("Não foi possível obter os cursos", ex.Message));
            }
        }

        public IActionResult Cadastrar()
        {
            return View(new CursoViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(CursoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var curso = new CursoRequest(model.Nome, model.Turno, model.Curriculos);
                    await _cursoService.Cadastrar(curso);
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("",ex.Message);
            }            
            return View(model);
        }

        public async Task<IActionResult> Editar(int id)
        {
            Curso curso = await _cursoService.ObterComCurriculos(id);
            var curriculoAtuais = new List<CurriculoResponse>();
            foreach (var item in curso.Curriculos)
                curriculoAtuais.Add(new CurriculoResponse(item.CurriculoId, item.Nome));

            CursoEditViewModel viewModel = curso.ToCursoEditViewModel();
            List<Curriculo> curriculos = await _curriculoService.ObterTodos();
            viewModel.CurriculosPossiveis = curriculos.Select(c => c.ToCurriculoResponse())
                                                      .ToList();
            viewModel.CurriculosAtuais = curriculoAtuais;
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, CursoEditViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CursoEditRequest request = model.ToCursoEditRequest();
                    await _cursoService.Atualizar(request);
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Deletar(int id)
        {
            try
            {
                await _cursoService.Deletar(id);
                return Json(new SucessoResponse("Removido com sucesso."));
            }
            catch (Exception ex)
            {
                return Json(new ErroResponse("Não foi possível remover o curso", ex.Message));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Desativar(int id)
        {
            try
            {
                await _cursoService.Desativar(id);
                return Json(new SucessoResponse("Curso desativado com sucesso"));
            }
            catch (Exception ex)
            {
                return Json(new ErroResponse("Não foi possível desativar o curso", ex.Message));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Ativar(int id)
        {
            try
            {
                await _cursoService.Ativar(id);
                return Json(new SucessoResponse("Curso ativado com sucesso"));
            }
            catch (Exception ex)
            {
                return Json(new ErroResponse("Não foi possível ativar o curso", ex.Message));
            }
        }
    }
}

src/SysMatriculas.Web/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SysMatriculas.Dominio;
using SysMatriculas.Web.ViewModels;
using System.Threading.Tasks;

namespace SysMatriculas.Web.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly UserManager<Usuario> _userManager;

        public MenuViewComponent(UserManager<Usuario> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            if (currentUser == null)
                return View();

            bool coordenador = User.IsInRole("Coordenador");
            var model = new MenuComponent
            {
                Nome = currentUser.Nome,
                Email = currentUser.Email,
                Login = currentUser.UserName,
                TipoDeUsuario = User.IsInRole("Coordenador") ? "Coordenador": "Aluno"
            };
            return View(model);
        }
    }
}

src/SysMatriculas.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SysMatriculas.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SysMatriculas.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Curso" asp-action="Index">Cursos</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - SysMatriculas.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/SysMatriculas.Web/Views/Shared/_LayoutAdminLTE.cshtml
@addTagHelper *, MyWebApp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema de matriculas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        @*<link rel="stylesheet" href="~/lib/Ionicons/css/ionicons.min.css">*@
        <link rel="stylesheet" href="~/lib/admin-lte/dist/css/AdminLTE.min.css">
        <link rel="stylesheet" href="~/lib/admin-lte/dist/css/skins/skin-blue.min.css">
        <link rel="stylesheet" href="~/lib/sweetalert/sweetalert2.min.css" />
        <link rel="stylesheet" href="~/css/styles.css" />
        @*<link rel="stylesheet" href="~/css/adminlte.custom.css" />*@
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute" />
        @*<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />*@
    </environment>
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">...</span>

                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">Sistema de matriculas</span>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/lib/admin-lte/dist/img/avatar5.png" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        @await Component.InvokeAsync("UsuarioPerfil")
                    </div>
                </div>

                <!-- Sidebar Menu -->
                @await Component.InvokeAsync("Menu")
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="pull-right hidden-xs">
                <p>&copy; 2019 - Jogos de palavras</p>
            </div>
            <!-- Default to the left -->
            &nbsp;
        </footer>

    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/admin-lte/dist/js/adminlte.js"></script>
        <script src="~/lib/sweetalert/sweetalert2.all.min.js"></script>
        <script src="~/js/ModalManager.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/SysMatriculas.Web/Views/Shared/_LayoutAdminLTELogin.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Sistema de matrículas</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
            <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css"/>
            <link rel="stylesheet" href="~/lib/admin-lte/dist/css/AdminLTE.min.css"/>
        </environment>

        <environment exclude="Development">
            <link rel="stylesheet"
                  href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only"
                  asp-fallback-test-property="position"
                  asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
        <style>
            body {
                padding-top: 0px;
                padding-bottom: 0px;
                background-color: #222D32 !important;
            }
            .login-logo a {
                color:#fff;
            }
            .btn-primary {
                background-color: #fff;
                border: 2px solid #222D32;
                color: #222D32;
                border-width: 2px;
                transition: .4s all;
            }
                .btn-primary:hover {
                    border: 2px solid #222D32;
                    border-width: 2px;
                    background-color: #222D32;
                    transition: .4s all;
                }
                .btn-primary:focus,
                .btn-primary:active {
                    background-color: #222D32;
                    transition: .4s all;
                }
                .btn-primary:hover, .btn-primary:active, .btn-primary.hover {
                    background-color: #222D32;
                    transition: .4s all;
                }
                .btn:focus,
                .btn-primary.active,
                .btn-primary.focus, .btn-primary:focus {
                    background-color: #222D32;
                    transition: .4s all;
                }
        </style>
    </head>
    <body class="hold-transition login-page">
        @RenderBody()
        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
        </environment>
        <environment exclude="Development"></environment>
    </body>
    @RenderSection("Scripts", required: false)
</html>

src/SysMatriculas.Web/Views/Shared/_LayoutDesempenho.cshtml
@addTagHelper *, MyWebApp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema de matriculas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        @*<link rel="stylesheet" href="~/lib/Ionicons/css/ionicons.min.css">*@
        <link rel="stylesheet" href="~/lib/admin-lte/dist/css/AdminLTE.min.css">
        <link rel="stylesheet" href="~/lib/admin-lte/dist/css/skins/skin-blue.min.css">
        <link rel="stylesheet" href="~/lib/sweetalert/sweetalert2.min.css" />
        <link rel="stylesheet" href="~/css/styles.css" />
        @*<link rel="stylesheet" href="~/css/adminlte.custom.css" />*@
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute" />
        @*<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />*@
    </environment>
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">...</span>

                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">Sistema de matriculas</span>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/lib/admin-lte/dist/img/avatar5.png" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        @await Component.InvokeAsync("UsuarioPerfil")
                    </div>
                </div>

                <!-- Sidebar Menu -->
                @await Component.InvokeAsync("Menu")
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="pull-right hidden-xs">
                <p>&copy; 2019 - Jogos de palavras</p>
            </div>
            <!-- Default to the left -->
            &nbsp;
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/admin-lte/dist/js/adminlte.js"></script>
        <script src="~/lib/sweetalert/sweetalert2.all.min.js"></script>
        <script src="~/js/ModalManager.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/SysMatriculas.Web/Views/Shared/_ListScriptsPartial.cshtml
<environment include="Development">
    <script src="~/js/dataTables/DataTablesAuxiliadores.js"></script>
    <script src="~/lib/datatables/datatables1.10.13.min.js"></script>
</environment>
<environment exclude="Development">
    @*<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
            asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator"
            crossorigin="anonymous"
            integrity="sha384-rZfj/ogBloos6wzLGpPkkOr/gpkBNLZ6b6yLy4o+ok+t/SAKlL5mvXLr0OXNi1Hp">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.9/jquery.validate.unobtrusive.min.js"
            asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive"
            crossorigin="anonymous"
            integrity="sha384-ifv0TYDWxBHzvAk2Z0n8R434FL1Rlv/Av18DXE43N/1rvHyOG4izKst0f2iSLdds">
    </script>*@
</environment>