src/SysMatriculas.Web/Controllers/DisciplinaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SysMatriculas.Dominio;
using SysMatriculas.Dominio.Requests;
using SysMatriculas.Dominio.Responses;
using SysMatriculas.Negocio.Services.Interfaces;
using SysMatriculas.Persistencia.DTOs.DataTables;
using SysMatriculas.Web.Extensions;
using SysMatriculas.Web.Helpers;
using SysMatriculas.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SysMatriculas.Web.Controllers
{
    [Authorize(Roles = "Coordenador")]
    public class DisciplinaController : Controller
    {
        private IDisciplinaService _disciplinaService;
        private ICurriculoService _curriculoService;
        private ICursoService _cursoService;
        private ISelectListItemHelper _selectListHelper;

        public DisciplinaController(IDisciplinaService disciplinaService,
                                    ICurriculoService curriculoService,
                                    ICursoService cursoService,
                                    ISelectListItemHelper selectListHelper)
        {
            _disciplinaService = disciplinaService;
            _curriculoService = curriculoService;
            _cursoService = cursoService;
            _selectListHelper = selectListHelper;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Curriculos = await _curriculoService.ObterParaFiltros();
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Listar(DataTableRequestDisciplinas request)
        {
            var disciplinasPaginados = await _disciplinaService.ObterListaPaginada(request);

            return Json(new
            {
                request.draw,
                recordsTotal = disciplinasPaginados.RecordsTotal,
                recordsFiltered = disciplinasPaginados.RecordsFiltered,
                data = disciplinasPaginados.Itens
            });         
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Deletar(int id)
        {
            try
            {
                await _disciplinaService.Deletar(id);
                return Json(new SucessoResponse("Disciplina removida com sucesso."));
            }
            catch (Exception ex)
            {
                return Json(new ErroResponse("Não foi possível remover as disciplinas.", ex.Message));
            }
        }

        public async Task<IActionResult> Cadastrar()
        {
            List<SelectListItem> selectListItems = await _selectListHelper.ObterCurriculosSelectList();
            var viewModel = new DisciplinaCadastroViewModel(selectListItems);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cadastrar(DisciplinaCadastroViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Não foi possível cadastrar a disciplina");
                model.CurriculosDisponiveis = await _selectListHelper.ObterCurriculosSelectList();
                return View(model);
            }

            DisciplinaRequest disciplina = model.ToDisciplinaRequest();
            await _disciplinaService.Cadastrar(disciplina);
            return RedirectToAction("index");
        }

        public async Task<IActionResult> Editar(int id)
        {
            Disciplina disciplina = await _disciplinaService.Obter(id);
            DisciplinaEdicaoViewModel model = disciplina.ToDisciplinaEdicaoViewModel();
            model.CurriculosDisponiveis = await _selectListHelper.ObterCurriculosSelectList();
            model.PreRequisitosDisponiveis = await _selectListHelper.ObterSelectListDisciplinas(disciplina.CurriculoId,disciplina.DisciplinaId);
            model.CoRequisitosDisponiveis = model.PreRequisitosDisponiveis;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(DisciplinaEdicaoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    DisciplinaRequest disciplina = model.ToDisciplinaRequest();
                    await _disciplinaService.Atualizar(disciplina);
                    return RedirectToAction("Index");
                }
            }
            catch 
            {
                ModelState.AddModelError("", "Não foi possível atualizar a disciplina.");
            }

            List<SelectListItem> disciplinasSelectList = await _selectListHelper.ObterSelectListDisciplinas((int)model.CurriculoId, model.DisciplinaId);
            model.PreRequisitosDisponiveis = disciplinasSelectList;
            model.CoRequisitosDisponiveis = disciplinasSelectList;
            model.CurriculosDisponiveis = await _selectListHelper.ObterCurriculosSelectList();
            return View(model);
        }


        public async Task<JsonResult> ObterDisciplinasDoCurriculo(int id)
        {
            try
            {
                List<Disciplina> disciplinasItens = await _disciplinaService.ObterTodasDoCurriculo(id);
                List<DisciplinaResponse> disciplinas = disciplinasItens.Select(item => item.ToDisciplinaResponse()).ToList();
                return Json(new { sucesso = true, disciplinas });
            }
            catch (Exception ex)
            {
                return Json(new ErroResponse("Não foi possível obter uma lista de disciplinas.", ex.Message));
            }
        }

        
    }
}

src/SysMatriculas.Web/Views/Disciplina/Cadastrar.cshtml
@model SysMatriculas.Web.ViewModels.DisciplinaCadastroViewModel

@{
    ViewData["Title"] = "Cadastrar Disciplinas";
    Layout = "~/Views/Shared/_LayoutAdminLTE.cshtml";
}
<section class="content-header">
    <h1>
        Disciplinas
        <small>Cadastrar Disciplinas</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-action="Index">
                <i class="fa fa-home"></i> Disciplinas
            </a>
        </li>
        <li class="active">
            Cadastrar Disciplinas
        </li>
    </ol>
</section>
<section class="content container-fluid">
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title">
                Informe os dados abaixo e clique em salvar
            </h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <form asp-action="Cadastrar" id="form-cadastro">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="Nome" class="control-label"></label>
                                    <input asp-for="Nome" class="form-control" />
                                    <span asp-validation-for="Nome" class="text-danger"></span>
                                </div>
                            </div>
                            
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="CurriculoId" class="control-label">Currículo</label>
                                    <select asp-for="CurriculoId" asp-items="Model.CurriculosDisponiveis"
                                            class="form-control">
                                        <option value="">Selecione um curriculo...</option>
                                    </select>
                                    <span asp-validation-for="CurriculoId"
                                          class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="CargaHoraria" class="control-label">Carga horária</label>
                                    <input asp-for="CargaHoraria" class="form-control" />
                                    <span asp-validation-for="CargaHoraria" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="Semestre" class="control-label">Semestre</label>
                                    <input asp-for="Semestre" class="form-control" />
                                    <span asp-validation-for="Semestre" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="PreRequisitos" class="control-label">Pré requisitos</label>
                                    <select asp-for="PreRequisitos" disabled="disabled" class="form-control"></select>
                                    <span asp-validation-for="PreRequisitos" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="CoRequisitos" class="control-label">Co-requisitos</label>
                                    <select asp-for="CoRequisitos" disabled="disabled" class="form-control"></select>
                                    <span asp-validation-for="CoRequisitos" class="text-danger"></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <a class="btn btn-warning" asp-action="Index">
                                <i class="fa fa-chevron-left"></i> Voltar
                            </a>
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-save"></i> Salvar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/disciplinas/CadastroDisciplina.js"></script>
    <script>
        window.cadastroDisciplina = new CadastroDisciplina();
    </script>
}

src/SysMatriculas.Web/Views/Disciplina/Editar.cshtml
@model SysMatriculas.Web.ViewModels.DisciplinaEdicaoViewModel

@{
    ViewData["Title"] = "Editar Disciplinas";
    Layout = "~/Views/Shared/_LayoutAdminLTE.cshtml";
}
<section class="content-header">
    <h1>
        Disciplinas
        <small>Editar Disciplinas</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-action="Index">
                <i class="fa fa-home"></i> Disciplinas
            </a>
        </li>
        <li class="active">
            Editar Disciplinas
        </li>
    </ol>
</section>
<section class="content container-fluid">
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title">
                Informe os dados abaixo e clique em salvar
            </h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <form asp-action="Editar" id="form-cadastro">
                        <input asp-for="DisciplinaId" type="hidden" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="Nome" class="control-label"></label>
                                    <input asp-for="Nome" class="form-control" />
                                    <span asp-validation-for="Nome" class="text-danger"></span>
                                </div>
                            </div>
                            
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="CurriculoId" class="control-label">Currículo</label>
                                    <select asp-for="CurriculoId" asp-items="Model.CurriculosDisponiveis"
                                            class="form-control">
                                        <option value="">Selecione um curriculo...</option>
                                    </select>
                                    <span asp-validation-for="CurriculoId"
                                          class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="CargaHoraria" class="control-label">Carga horária</label>
                                    <input asp-for="CargaHoraria" class="form-control" />
                                    <span asp-validation-for="CargaHoraria" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="Semestre" class="control-label">Semestre</label>
                                    <input asp-for="Semestre" class="form-control" />
                                    <span asp-validation-for="Semestre" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="PreRequisitos" class="control-label">Pré requisitos</label>
                                    <select asp-for="PreRequisitos" asp-items="@Model.PreRequisitosDisponiveis" class="form-control">
                                    </select>
                                    <span asp-validation-for="PreRequisitos" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="CoRequisitos" class="control-label">Co-requisitos</label>
                                    <select asp-for="CoRequisitos" asp-items="@Model.CoRequisitosDisponiveis" class="form-control">
                                    </select>
                                    <span asp-validation-for="CoRequisitos" class="text-danger"></span>
                                    
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <a class="btn btn-warning" asp-action="Index">
                                <i class="fa fa-chevron-left"></i> Voltar
                            </a>
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-save"></i> Salvar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/disciplinas/CadastroDisciplina.js"></script>
    <script>
        window.cadastroDisciplina = new CadastroDisciplina();
    </script>
}

src/SysMatriculas.Web/Views/Disciplina/Index.cshtml
@{
    ViewData["Title"] = "Lista de Disciplinas";
    Layout = "~/Views/Shared/_LayoutAdminLTE.cshtml";
}
<link href="~/lib/datatables/datatables.1.10.13.min.css" rel="stylesheet" />

<section class="content-header">
    <h1>
        Disciplinas
        <small>Lista de Disciplinas</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-action="Index">
                <i class="fa fa-home"></i> Disciplinas
            </a>
        </li>
        <li class="active">
            Lista de Disciplinas
        </li>
    </ol>
</section>
<section class="content container-fluid">
    @Html.AntiForgeryToken()
    
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group form-inline">
                        <label class="control-label">Pesquisa:</label>
                        <input class="form-control" id="pesquisa" name="pesquisa" />

                        <label class="control-label">Currículo:</label>

                        <select id="curriculoId" name="curriculoId" class="form-control">
                            <option value="">Selecione</option>
                            @foreach (var item in (List<KeyValuePair<string,string>>)ViewBag.Curriculos)
                            {
                                <option value="@item.Value">@item.Key</option>
                            }
                        </select>
                    </div>
                    <table id="tb-disciplina"
                           class="table table-striped table-bordered "
                           style="width:100%">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Nome</th>
                                <th>Curriculo</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                        
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <p>
                <a class="btn btn-primary" asp-controller="Disciplina"
                   asp-action="Cadastrar">Cadastrar</a>
            </p>
        </div>
    </div>
</section>
@section Scripts {
    @{await Html.RenderPartialAsync("_ListScriptsPartial");}
    <script src="~/js/disciplinas/DisciplinasLista.js"></script>
    <script>
        window.dataTablesAux = new DataTablesAuxiliadores();
        window.disciplinasLista = new DisciplinasLista();
    </script>
}