src/SysMatriculas.Web/Controllers/CurriculoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SysMatriculas.Dominio;
using SysMatriculas.Dominio.Responses;
using SysMatriculas.Negocio.Exceptions;
using SysMatriculas.Negocio.Services.Interfaces;
using SysMatriculas.Persistencia.DTOs.DataTables;
using SysMatriculas.Web.Helpers;
using System;
using System.Threading.Tasks;

namespace SysMatriculas.Web.Controllers;

[Authorize(Roles = "Coordenador")]
public class CurriculoController : Controller
{
    private readonly ICurriculoService _curriculoService;
    private readonly ISelectListItemHelper _selectListHelper;

    public CurriculoController(ICurriculoService serviceCurriculo,
                               ISelectListItemHelper selectListItemHelper)
    {
        _curriculoService = serviceCurriculo;
        _selectListHelper = selectListItemHelper;
    }

    public ActionResult Index() => View();

    public async Task<JsonResult> ObterLista() => Json(await _curriculoService.ObterEmDTOs());

    [HttpPost]
    public async Task<JsonResult> Listar(DataTableRequest request) => Json(await _curriculoService.ObterListaPaginada(request));

    public async Task<IActionResult> Cadastrar()
    {
        ViewBag.Cursos = await _selectListHelper.ObterCursos();
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Cadastrar(Curriculo curriculo, IFormCollection collection)
    {
        try
        {
            if (ModelState.IsValid)
            {
                await _curriculoService.Cadastrar(curriculo);
                return RedirectToAction(nameof(Index));
            }
        }
        catch (CurriculoJaCadastradoException ex)
        {
            ModelState.AddModelError("", ex.Message);
        }
        catch (Exception ex)
        {
            ModelState.AddModelError("", ex.Message);
        }
        ViewBag.Cursos = await _selectListHelper.ObterCursos();
        return View(curriculo);            
    }

    public async Task<ActionResult> Editar(int id)
    {
        Curriculo curriculo = await _curriculoService.Obter(id);
        ViewBag.Cursos = await _selectListHelper.ObterCursos();
        return View(curriculo);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Editar(Curriculo model)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("", "Não foi possivel atualizar o currículo.");
            ViewBag.Cursos = await _selectListHelper.ObterCursos();
            return View(model);
        }

        var request = new CurriculoRequest(model.CurriculoId, model.Nome);
        await _curriculoService.Atualizar(request);
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<JsonResult> Deletar(int id, IFormCollection collection)
    {
        try
        {
            await _curriculoService.Delete(id);
            return Json(new { sucesso = true });
        }
        catch (CurriculoEmUsoException ex)
        {
            return Json(new ErroResponse("Não foi possível remover o currículo pois ele esta em uso.", ex.Message));
        }
        catch (Exception ex)
        {
            return Json(new ErroResponse("Não foi possível remover o currículo.", ex.Message));
        }
    }
}

src/SysMatriculas.Web/Controllers/CursoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SysMatriculas.Dominio;
using SysMatriculas.Dominio.Requests;
using SysMatriculas.Dominio.Responses;
using SysMatriculas.Negocio.Services.Interfaces;
using SysMatriculas.Persistencia.DTOs.DataTables;
using SysMatriculas.Web.Extensions;
using SysMatriculas.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SysMatriculas.Web.Controllers
{
    [Authorize(Roles = "Coordenador")]
    public class CursoController : Controller
    {
        private ICursoService _cursoService;
        private ICurriculoService _curriculoService;

        public CursoController(
            ICursoService cursoService,
            ICurriculoService curriculoService)
        {
            _cursoService = cursoService;
            _curriculoService = curriculoService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Listar(DataTableRequest request)
        {
            try
            {
                var cursosPaginados = await _cursoService.ObterListaPaginada(request);
                return Json(new
                {
                    request.draw,
                    recordsTotal = cursosPaginados.RecordsTotal,
                    recordsFiltered = cursosPaginados.RecordsFiltered,
                    data = cursosPaginados.Itens
                });
            }
            catch (Exception ex)
            {
                return Json(new ErroResponse("Não foi possível obter os cursos", ex.Message));
            }
        }

        public IActionResult Cadastrar()
        {
            return View(new CursoViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(CursoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var curso = new CursoRequest(model.Nome, model.Turno, model.Curriculos);
                    await _cursoService.Cadastrar(curso);
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("",ex.Message);
            }            
            return View(model);
        }

        public async Task<IActionResult> Editar(int id)
        {
            Curso curso = await _cursoService.ObterComCurriculos(id);
            var curriculoAtuais = new List<CurriculoResponse>();
            foreach (var item in curso.Curriculos)
                curriculoAtuais.Add(new CurriculoResponse(item.CurriculoId, item.Nome));

            CursoEditViewModel viewModel = curso.ToCursoEditViewModel();
            List<Curriculo> curriculos = await _curriculoService.ObterTodos();
            viewModel.CurriculosPossiveis = curriculos.Select(c => c.ToCurriculoResponse())
                                                      .ToList();
            viewModel.CurriculosAtuais = curriculoAtuais;
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, CursoEditViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CursoEditRequest request = model.ToCursoEditRequest();
                    await _cursoService.Atualizar(request);
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Deletar(int id)
        {
            try
            {
                await _cursoService.Deletar(id);
                return Json(new SucessoResponse("Removido com sucesso."));
            }
            catch (Exception ex)
            {
                return Json(new ErroResponse("Não foi possível remover o curso", ex.Message));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Desativar(int id)
        {
            try
            {
                await _cursoService.Desativar(id);
                return Json(new SucessoResponse("Curso desativado com sucesso"));
            }
            catch (Exception ex)
            {
                return Json(new ErroResponse("Não foi possível desativar o curso", ex.Message));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Ativar(int id)
        {
            try
            {
                await _cursoService.Ativar(id);
                return Json(new SucessoResponse("Curso ativado com sucesso"));
            }
            catch (Exception ex)
            {
                return Json(new ErroResponse("Não foi possível ativar o curso", ex.Message));
            }
        }
    }
}

src/SysMatriculas.Web/Views/Shared/Components/Menu/Default.cshtml
@addTagHelper *, MyWebApp
@model SysMatriculas.Web.ViewModels.MenuComponent

@if (Model.TipoDeUsuario == "Aluno")
{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MENU</li>
        <li data-tipo="Progresso">
            <a asp-area="" asp-controller="Aluno" asp-action="Curriculos">
                <i class="fa fa-book"></i>
                <span>Ver progresso</span>
            </a>
        </li>
        <li data-tipo="Dashboard">
            <a asp-area="" asp-controller="Aluno" asp-action="Desempenho">
                <i class="fa fa-dashboard"></i>
                <span>Meu Desempenho</span>
            </a>
        </li>
        @*<li data-tipo="MeuPerfil">
            <a asp-area="" asp-controller="Aluno" asp-action="MeuPerfil">
                <i class="fa fa-dashboard"></i>
                <span>Meu Desempenho</span>
            </a>
        </li>*@
    </ul>
}
else
{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MENU</li>
        <li data-tipo="Cursos">
            <a asp-area="" asp-controller="Curso" asp-action="index">
                <i class="fa fa-cubes"></i>
                <span>Cursos</span>
            </a>
        </li>
        <li data-tipo="Curriculos">
            <a asp-area="" asp-controller="Curriculo" asp-action="Index">
                <i class="fa fa-book"></i>
                <span>Currículos</span>
            </a>
        </li>
        <li data-tipo="Disciplina">
            <a asp-area="" asp-controller="Disciplina" asp-action="Index">
                <i class="fa fa-book"></i>
                <span>Disciplinas</span>
            </a>
        </li>

        <li data-tipo="Usuarios">
            <a asp-area="" asp-controller="usuario" asp-action="Index">
                <i class="fa fa-user"></i>
                <span>Coordenadores</span>
            </a>
        </li>
        <li data-tipo="Alunos">
            <a asp-area="" asp-controller="aluno" asp-action="Index">
                <i class="fa fa-user"></i>
                <span>Alunos</span>
            </a>
        </li>
    </ul>
}